server:
  port: 8050

cloud:
  aws:
    credentials:
      access-key: AKIASQFSAJE5DW44PSON
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false


application:
  bucket:
    name: potatovelog

spring:
  application:
    name: potato-velog-board
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.velog.veloguser: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh
