server:
  port: 8070

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: potato-velog-gateway
  cloud:
    gateway:
      routes:
        - id: potato-velog-user
          uri: lb://POTATO-VELOG-USER
          predicates:
            - Path=/potato-velog-user/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/potato-velog-user/(?<segment>.*), /$\{segment}
        - id: potato-velog-user
          uri: lb://POTATO-VELOG-USER
          predicates:
            - Path=/potato-velog-user/createUser
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/potato-velog-user/(?<segment>.*), /$\{segment}
        - id: potato-velog-user
          uri: lb://POTATO-VELOG-USER
          predicates:
            - Path=/potato-velog-user/wasCheck
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/potato-velog-user/(?<segment>.*), /$\{segment}
        - id: potato-velog-user
          uri: lb://POTATO-VELOG-USER
          predicates:
            - Path=/potato-velog-user/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/potato-velog-user/(?<segment>.*), /$\{segment}
        - id: potato-velog-user
          uri: lb://POTATO-VELOG-USER
          predicates:
            - Path=/potato-velog-user/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/potato-velog-user/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: potato-velog-board
          uri: lb://POTATO-VELOG-BOARD
          predicates:
            - Path=/potato-velog-board/**
token:
  secret: potato_velog

management:
  endpoints:
    web:
      exposure:
        include: refresh, beans, health, httptrace
